<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.erlwood.knime</groupId>
		<artifactId>erlwood-knime</artifactId>
		<version>4.5.1-SNAPSHOT</version>
		<relativePath>../../pom.xml</relativePath>
	</parent>
	<artifactId>org.erlwood.knime.webservice.core</artifactId>
	<packaging>eclipse-plugin</packaging>

	<properties>
		<httpclient.version>4.5.3</httpclient.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-bundle-libs</id>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>com.fasterxml.woodstox</groupId>
									<artifactId>woodstox-core</artifactId>
									<version>6.2.1</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.activation</groupId>
									<artifactId>jakarta.activation</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.mail</groupId>
									<artifactId>jakarta.mail</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.bind</groupId>
									<artifactId>jaxb-core</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.bind</groupId>
									<artifactId>jaxb-impl</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.fastinfoset</groupId>
									<artifactId>FastInfoset</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.messaging.saaj</groupId>
									<artifactId>saaj-impl</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.stream.buffer</groupId>
									<artifactId>streambuffer</artifactId>
									<version>2.0.1</version>
								</artifactItem>
								<artifactItem>
									<groupId>com.sun.xml.ws</groupId>
									<artifactId>jaxws-rt</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>commons-codec</groupId>
									<artifactId>commons-codec</artifactId>
									<version>1.9</version>
								</artifactItem>
								<artifactItem>
									<groupId>commons-logging</groupId>
									<artifactId>commons-logging</artifactId>
									<version>1.2</version>
								</artifactItem>
								<artifactItem>
									<groupId>jakarta.annotation</groupId>
									<artifactId>jakarta.annotation-api</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>jakarta.jws</groupId>
									<artifactId>jakarta.jws-api</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>jakarta.xml.bind</groupId>
									<artifactId>jakarta.xml.bind-api</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>jakarta.xml.soap</groupId>
									<artifactId>jakarta.xml.soap-api</artifactId>
									<version>2.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>jakarta.xml.ws</groupId>
									<artifactId>jakarta.xml.ws-api</artifactId>
									<version>3.0.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>net.java.dev.jna</groupId>
									<artifactId>jna</artifactId>
									<version>4.1.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>net.java.dev.jna</groupId>
									<artifactId>jna-platform</artifactId>
									<version>4.1.0</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents</groupId>
									<artifactId>httpclient</artifactId>
									<version>${httpclient.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents</groupId>
									<artifactId>httpclient-win</artifactId>
									<version>${httpclient.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents</groupId>
									<artifactId>httpcore</artifactId>
									<version>4.4.6</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.apache.httpcomponents</groupId>
									<artifactId>httpmime</artifactId>
									<version>${httpclient.version}</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.codehaus.woodstox</groupId>
									<artifactId>stax2-api</artifactId>
									<version>4.2.1</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.glassfish.external</groupId>
									<artifactId>management-api</artifactId>
									<version>3.2.3</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.glassfish.gmbal</groupId>
									<artifactId>gmbal-api-only</artifactId>
									<version>4.0.2</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.glassfish.ha</groupId>
									<artifactId>ha-api</artifactId>
									<version>3.1.12</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.jvnet.mimepull</groupId>
									<artifactId>mimepull</artifactId>
									<version>1.9.13</version>
								</artifactItem>
								<artifactItem>
									<groupId>org.jvnet.staxex</groupId>
									<artifactId>stax-ex</artifactId>
									<version>2.0.0</version>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
